configuration: 
  name: hellobioqa
  author: team15
  
persistence-provider:
  inherit: helloqa.db.local-persistence-provider

collection-reader:
  inherit: hellobioqa.collection.decorated-collection-reader
  dataset: TRECGEN06
  file: /input/trecgen06.txt

pipeline:
  - inherit: jdbc.sqlite.cse.phase
    name: keyterm-extractor
    options: |
      - inherit: helloqa.keyterm.simple
      - inherit: hellobioqa.team15.keyterm.luzhengsKeytermExtractorDescriptor
      - inherit: hellobioqa.team15.keyterm.CthayurLingPipeKeyTerm
      
  - inherit: jdbc.sqlite.cse.phase 
    name: retrieval-strategist
    options: |
      - inherit: hellobioqa.team15.retrieval.mingyans-solr-strategist
      - inherit: hellobioqa.team15.retrieval.solr-fuzzy-variant-strategist
      - inherit: hellobioqa.team15.retrieval.simple-solr-strategist
          
  - inherit: jdbc.sqlite.cse.phase  
    name: passage-extractor
    options: |
      - inherit: hellobioqa.team15.passage.mingyans-passage
      
  - inherit: helloqa.eval.keyterm-aggregator-consumer

  - inherit: jdbc.eval.retrieval-aggregator-consumer
      
  - inherit: helloqa.eval.passage-map-aggregator-consumer      
    
post-process: 
  - inherit: helloqa.eval.keyterm-evaluator-consumer
  - inherit: report.csv-report-generator
    builders: |
      - inherit: helloqa.report.keyterm-report-component

  - inherit: jdbc.eval.retrieval-evaluator-consumer
  - inherit: report.csv-report-generator
    builders: |
      - inherit: jdbc.report.f-measure-report-component
          
  - inherit: helloqa.eval.passage-map-evaluator-consumer
  - inherit: report.csv-report-generator
    builders: |
      - inherit: helloqa.report.map-report-component
  
